export interface Product {
  id: string;
  title: string;
  brand: string;
  category: string;
  description: string;
  badge?: string;
  price?: string;
  imageUrl?: string;
  specs: Record<string, string>;
  features: string[];
  datasheetUrl?: string;
}

export const brands = [ "ELCO", "EUCHNER", "SICK", "Siemens", "ABB", "Schneider", "Rockwell", "Mitsubishi", "Honeywell"] as const;
export type Brand = (typeof brands)[number];

/** Brand logos from assets (see src/data/brandLogos.ts). Used when product has no imageUrl. */
import { brandLogoUrls } from "./brandLogos";

export const brandThumbnails: Record<string, string> = brandLogoUrls;

/** Default product image when no product image or brand logo is available. */
export const defaultProductPlaceholder = "/placeholder.svg";

/** Returns product image URL or brand thumbnail fallback. */
export function getProductDisplayImage(product: Product): string | undefined {
  return product.imageUrl ?? brandThumbnails[product.brand];
}

export const categories = ["All", "PLC & Controllers", "Drives & Motors", "Switchgear", "HMI & SCADA", "Safety", "Sensors", "Power Distribution", "Connectivity", "I/O Modules"] as const;

/** Product datasheets: from Vercel Blob when VITE_BLOB_STORAGE_BASE_URL is set, else local dummy. Replace with per-product URLs later. */
const blobBase = import.meta.env.VITE_BLOB_STORAGE_BASE_URL as string | undefined;
export const defaultDatasheetUrl =
  blobBase && blobBase.length > 0
    ? `${blobBase.replace(/\/$/, "")}/01-SIEMENS-S7-1500-Datasheet.pdf`
    : "/datasheets/dummy-datasheet.pdf";

export const defaultProducts: Product[] = [
  // ── SIEMENS ──
  { id: "s1", title: "SIMATIC S7-1500 PLC", brand: "Siemens", category: "PLC & Controllers", description: "High-performance PLC for complex automation with integrated security and motion control.", badge: "Popular", price: "Contact for pricing", specs: { "Model Numbers": "CPU 1511-1 PN (6ES7511-1AL03), 1513-1 PN (6ES7513-1AL00), 1515-2 PN, 1516-3 PN, 1517-3 PN, 1517H-4 PN (redundant)", "Processing Time": "1 ns/bit (FS04) to 60 ns", "Memory": "Up to 20 MB work, 32 GB load (SMC)", "Interfaces": "PROFINET IRT, 2-port switch", "I/O Points": "Up to 65,536", "Programming": "TIA Portal", "Protection": "IP20 / IP65/67" }, features: ["Integrated motion control", "Fail-safe variants available", "OPC UA server built-in", "Web server for diagnostics"], datasheetUrl: defaultDatasheetUrl },
  { id: "s2", title: "SINAMICS G120 Drive", brand: "Siemens", category: "Drives & Motors", description: "Modular frequency converter for a wide range of motor applications up to 250 kW.", price: "₹45,000 – ₹8,50,000", specs: { "Power Range": "0.37 – 250 kW (0.5 – 400 hp)", "Voltage": "200V / 400V / 690V", "Frame Sizes": "FSA to FSGX", "Control": "V/f, Vector, Servo", "Communication": "PROFINET, USS", "Protection": "IP20 / IP55", "Safety": "SIL 2 / PL d, Safe Torque Off" }, features: ["Integrated safety functions", "Energy-saving mode", "Easy commissioning via TIA Portal", "Modular design"], datasheetUrl: defaultDatasheetUrl },
  { id: "s3", title: "SIMATIC HMI Comfort Panel", brand: "Siemens", category: "HMI & SCADA", description: "Widescreen touch panels from 7\" to 22\" with high resolution and advanced scripting.", price: "₹65,000 – ₹3,50,000", specs: { "Models": "KTP700, KTP900, KTP1200, KP1500, KP2200 (7\"–22\")", "Display": "7\" to 22\" widescreen", "Resolution": "Up to 1920×1080", "Touch": "Capacitive multi-touch", "Memory": "24 MB internal", "Interfaces": "PROFINET, Ethernet, USB, SD" }, features: ["Multi-touch gestures", "PDF & recipe management", "Remote access via Sm@rt Server", "Alarm system"], datasheetUrl: defaultDatasheetUrl },
  { id: "s4", title: "SENTRON PAC4200 Power Meter", brand: "Siemens", category: "Power Distribution", description: "Multi-functional power monitoring device for precise energy data acquisition.", badge: "Popular", price: "₹32,000", specs: { "Ordering No.": "7KM PAC4200", "Measurement": "V, I, P, Q, S, PF, f, THD", "Accuracy": "Class 0.5 (active energy)", "Display": "LCD backlit", "Communication": "Modbus TCP/RTU, BACnet", "Inputs": "3-phase 4-wire" }, features: ["THD measurement", "Data logging", "Demand monitoring", "BACnet optional"], datasheetUrl: defaultDatasheetUrl },
  { id: "s5", title: "SIRIUS 3RV2 Motor Starter", brand: "Siemens", category: "Switchgear", description: "Compact circuit breaker for motor protection up to 40A with high breaking capacity.", price: "₹2,800 – ₹12,000", specs: { "Model Range": "3RV2011 to 3RV2040", "Current Range": "0.1 – 40A", "Breaking Capacity": "100 kA (Icu)", "Mounting": "DIN rail", "Coordination": "Type 2", "Width": "45 mm" }, features: ["Push-in terminals", "Auxiliary contacts", "Trip indication", "Combination possible"], datasheetUrl: defaultDatasheetUrl },
  { id: "s6", title: "SCALANCE XC206-2 Switch", brand: "Siemens", category: "Connectivity", description: "Managed industrial Ethernet switch for PROFINET with 6 RJ45 and 2 FO ports.", price: "₹28,000", specs: { "Ordering No.": "6GK5206-2BS00-2AC2", "Ports": "6× RJ45, 2× FO (multimode)", "Speed": "10/100 Mbps", "Management": "Web, CLI, SNMP", "Redundancy": "MRP, RSTP", "Temperature": "-40 to +70°C" }, features: ["PROFINET conformance", "VLAN support", "Port mirroring", "Diagnostics via TIA Portal"], datasheetUrl: defaultDatasheetUrl },
  { id: "s7", title: "SIMATIC ET 200SP I/O", brand: "Siemens", category: "PLC & Controllers", description: "Compact distributed I/O system for PROFINET with high channel density.", price: "₹5,000 – ₹25,000/module", specs: { "BaseUnits": "BU15 (6ES7193-6BP...), BU20 series", "Modules": "DI/DQ 8–16ch, AI/AQ 4ch, F-DI/F-DQ, CM 4×IO-Link, AI Energy Meter", "Cycle Time": "250 µs", "Communication": "PROFINET IRT", "Hot Swap": "Yes", "Width": "15 mm per module" }, features: ["BaseUnit color coding", "Fail-safe modules available", "Compact 15mm width", "Multi-fieldbuses"], datasheetUrl: defaultDatasheetUrl },
  { id: "s8", title: "SITOP PSU8200 Power Supply", brand: "Siemens", category: "Power Distribution", description: "Reliable 24V DC power supply with wide-range input and high efficiency.", price: "₹8,500 – ₹35,000", specs: { "Models": "6EP1333 (5A), 6EP1334 (10A), 6EP1336 (20A), 6EP1337 (40A)", "Output": "24V DC, 5 / 10 / 20 / 40A", "Input": "120–230V AC, 110–220V DC", "Efficiency": "Up to 95%", "Protection": "OVP, OCP, SCP; parallel capable" }, features: ["Extra power for 5s at 150%", "LED diagnostics", "Parallel operation", "Slim design"], datasheetUrl: defaultDatasheetUrl },
  { id: "s9", title: "SIPART PS2 Positioner", brand: "Siemens", category: "Sensors", description: "Intelligent electropneumatic positioner for linear and rotary actuators.", price: "₹55,000", specs: { "Variants": "PS2 PA (4–20 mA), PS2 with HART", "Input": "4–20 mA / HART", "Supply": "1.4 – 6 bar", "Protection": "IP66/67", "Diagnostics": "Valve diagnostics", "Explosion": "ATEX optional" }, features: ["Auto-calibration", "Tight shut-off", "Partial stroke test", "NE107 diagnostics"], datasheetUrl: defaultDatasheetUrl },
  { id: "s10", title: "3VA Molded Case Breaker", brand: "Siemens", category: "Switchgear", description: "MCCB from 16A to 630A with electronic trip unit and communication capability.", price: "₹15,000 – ₹1,50,000", specs: { "Model Range": "3VA1 (16–63A), 3VA2 (63–160A), 3VA4 (160–630A)", "Current Range": "16 – 630A", "Breaking": "Up to 110 kA", "Trip Unit": "ETU (electronic)", "Poles": "3P / 4P", "Communication": "Modbus RTU/TCP optional" }, features: ["Adjustable protection", "Rotary handle option", "Metering functions", "Zone-selective interlocking"], datasheetUrl: defaultDatasheetUrl },
  { id: "s11", title: "SIMATIC S7-1200 PLC", brand: "Siemens", category: "PLC & Controllers", description: "Compact controller for simple to mid-range automation with onboard I/O.", badge: "Best Seller", price: "₹22,000 – ₹65,000", specs: { "Model Numbers": "CPU 1211C, 1212C, 1214C (6ES7214-1AG40), 1215C, 1217C", "Memory": "150 KB program/data, 4 MB load", "I/O": "14–30 DI/DO, 2–10 AI (onboard)", "Communication": "PROFINET, 2-port switch", "Motion": "Up to 4 axes", "Programming": "TIA Portal" }, features: ["Web server", "Data logging", "PID control", "Integrated Ethernet"], datasheetUrl: defaultDatasheetUrl },

  // ── ABB ──
  { id: "a1", title: "AC500 PLC Platform", brand: "ABB", category: "PLC & Controllers", description: "Scalable PLC platform for process and factory automation with IEC 61131-3.", badge: "New", price: "Contact for pricing", specs: { "CPU Variants": "PM554, PM564, PM565, PM566, PM567, PM571, PM581, PM582, PM584, PM597", "Memory": "Up to 16 MB", "I/O Modules": "S500 (S501–S509)", "Communication": "EtherCAT, PROFINET, Modbus", "Programming": "Automation Builder" }, features: ["Hot-swap I/O", "SD card logging", "Redundancy support", "Web visualization"], datasheetUrl: defaultDatasheetUrl },
  { id: "a2", title: "ACS580 General Purpose Drive", brand: "ABB", category: "Drives & Motors", description: "All-compatible drive with built-in safety, energy efficiency features up to 500 kW.", price: "₹35,000 – ₹12,00,000", specs: { "Models": "ACS580-01 (wall 0.75–250 kW), ACS580-04 (cabinet 250–500 kW)", "Frame Sizes": "R1–R9", "Power": "0.75 – 500 kW", "Voltage": "230 – 690V", "Control": "DTC, Scalar", "Safety": "STO SIL 3", "Protection": "IP21" }, features: ["Built-in EMC filter", "Energy calculator", "Bluetooth commissioning", "Coated boards standard"], datasheetUrl: defaultDatasheetUrl },
  { id: "a3", title: "ACS880 Industrial Drive", brand: "ABB", category: "Drives & Motors", description: "High-performance industrial drive with direct torque control for demanding applications.", price: "₹1,50,000 – ₹25,00,000", specs: { "Power": "0.55 – 6000 kW", "Control": "DTC", "Safety": "IEC 61508 SIL 3", "Cooling": "Air / Liquid", "Communication": "PROFINET, EtherNet/IP, Modbus, CANopen" }, features: ["Adaptive programming", "Built-in PLC", "Energy optimizer", "Motor identification"], datasheetUrl: defaultDatasheetUrl },
  { id: "a4", title: "Tmax XT Circuit Breaker", brand: "ABB", category: "Switchgear", description: "Molded case circuit breaker range from 160A to 1600A with microprocessor trip unit.", price: "₹35,000 – ₹4,00,000", specs: { "Current": "160 – 1600A", "Breaking": "Up to 150 kA", "Trip Unit": "Ekip Touch, Ekip Com", "Poles": "3P / 4P", "Communication": "Ekip Com (Modbus)" }, features: ["Touch screen trip unit", "Energy metering", "Zone selectivity", "Drawer version available"], datasheetUrl: defaultDatasheetUrl },
  { id: "a5", title: "Masterpact MTZ Breaker", brand: "ABB", category: "Switchgear", description: "Low voltage air circuit breaker for power distribution up to 6300A.", price: "Contact for pricing", specs: { "Current": "800 – 6300A", "Breaking": "Up to 150 kA", "Poles": "3P / 4P", "Trip Unit": "Micrologic", "Motorized": "Yes", "Communication": "Modbus / Ethernet" }, features: ["Digital metering", "Maintenance prediction", "Cybersecurity", "IoT ready"], datasheetUrl: defaultDatasheetUrl },
  { id: "a6", title: "CP600 HMI Panel", brand: "ABB", category: "HMI & SCADA", description: "Touch screen operator panels from 4.3\" to 15\" with robust aluminium front.", price: "₹25,000 – ₹1,80,000", specs: { "Models": "CP605, CP635, CP675, CP685, CP615", "Screen": "4.3\" – 15\" TFT", "Resolution": "Up to 1024×768", "Memory": "128 MB Flash", "Ports": "Ethernet, USB, Serial", "Protection": "IP66 front" }, features: ["Multi-protocol", "Recipe management", "PDF viewer", "Remote access"], datasheetUrl: defaultDatasheetUrl },
  { id: "a7", title: "PSTX Softstarter", brand: "ABB", category: "Drives & Motors", description: "Compact softstarter for smooth motor starting, reducing mechanical stress up to 1250A.", price: "₹18,000 – ₹3,50,000", specs: { "Current": "30 – 1250A", "Voltage": "208 – 690V", "Bypass": "Built-in up to 370A", "Communication": "Modbus, PROFIBUS", "Protection": "IP20" }, features: ["Torque control", "Jog function", "Motor protection", "Adaptive acceleration"], datasheetUrl: defaultDatasheetUrl },
  { id: "a8", title: "M102-M Motor Controller", brand: "ABB", category: "Drives & Motors", description: "Flexible electronic motor controller and protector up to 80A.", price: "₹12,000 – ₹45,000", specs: { "Current": "0.5 – 80A", "Voltage": "200 – 690V", "Functions": "Start/Stop/Protect", "Communication": "Modbus optional", "Display": "LED" }, features: ["Electronic overload", "Phase monitoring", "Ground fault", "Configurable I/O"], datasheetUrl: defaultDatasheetUrl },
  { id: "a9", title: "ABB Safety Relay RT9", brand: "ABB", category: "Safety", description: "Configurable safety relay for emergency stop, guard monitoring, and two-hand control.", price: "₹8,500", specs: { "Inputs": "2 safety inputs", "Outputs": "3 NO + 1 NC", "Safety Level": "Cat 4 / PLe", "Width": "22.5 mm", "Supply": "24V DC" }, features: ["Guided contacts", "LED status", "Auto/manual reset", "Screw/spring terminals"], datasheetUrl: defaultDatasheetUrl },
  { id: "a10", title: "ABB i-bus KNX System", brand: "ABB", category: "Connectivity", description: "Intelligent building automation system for lighting, HVAC, and blind control.", price: "₹5,000 – ₹35,000/module", specs: { "Protocol": "KNX TP", "Modules": "Switching, dimming, sensing", "Programming": "ETS", "Topology": "Bus, line, area", "Power": "29V DC bus" }, features: ["Open standard", "IP gateway", "Smartphone control", "Energy monitoring"], datasheetUrl: defaultDatasheetUrl },
  { id: "a11", title: "REF615 Protection Relay", brand: "ABB", category: "Power Distribution", description: "Feeder protection relay for MV distribution with advanced communication.", price: "₹1,20,000", specs: { "Series": "Relion® 615", "Protection": "50/51, 67, 27, 59, arc, cable fault", "Communication": "IEC 61850 Ed.1/2, DNP3, Modbus", "Process Bus": "IEC 61850-9-2 LE", "Mounting": "Withdrawable plug-in unit" }, features: ["Disturbance recording", "GOOSE", "IEEE 1588", "Event logging"], datasheetUrl: defaultDatasheetUrl },

  // ── SCHNEIDER ──
  { id: "sc1", title: "Modicon M340 PLC", brand: "Schneider", category: "PLC & Controllers", description: "Mid-range PLC for process and infrastructure applications with Ethernet backbone.", price: "₹55,000 – ₹2,50,000", specs: { "Model Numbers": "BMXP342000 (1024 DI, 256 AI), BMXP342010, BMXP342020", "Memory": "Up to 4 MB", "I/O": "Up to 1024 discrete, 256 analog", "Communication": "Ethernet, Modbus", "Scan Time": "< 1 ms", "Programming": "Unity Pro / EcoStruxure" }, features: ["Hot standby redundancy", "FDT/DTM support", "SD card backup", "Web server"], datasheetUrl: defaultDatasheetUrl },
  { id: "sc2", title: "Modicon M580 ePAC", brand: "Schneider", category: "PLC & Controllers", description: "Ethernet programmable automation controller for process and critical infrastructure.", badge: "Premium", price: "Contact for pricing", specs: { "Model Numbers": "BMEP58xxx (BMEP583040, etc.)", "Processor": "Dual-core", "Communication": "Native Ethernet", "Cybersecurity": "Achilles L2 certified", "I/O": "Up to 64,000 points", "Redundancy": "Hot standby" }, features: ["Native Ethernet backplane", "Cybersecurity built-in", "IEC 61850 support", "Open & connected"], datasheetUrl: defaultDatasheetUrl },
  { id: "sc3", title: "ATV630 Variable Speed Drive", brand: "Schneider", category: "Drives & Motors", description: "Process drive for pumps, fans, and compressors from 0.75 to 500 kW.", price: "₹40,000 – ₹9,00,000", specs: { "Power": "0.75 – 500 kW", "Voltage": "200 – 690V", "Control": "Sensorless vector", "Safety": "STO SIL 2", "Communication": "Ethernet, Modbus" }, features: ["Multi-pump control", "Embedded Ethernet", "Fire mode", "Energy dashboard"], datasheetUrl: defaultDatasheetUrl },
  { id: "sc4", title: "Masterpact MTZ Breaker", brand: "Schneider", category: "Switchgear", description: "Air circuit breaker for power distribution up to 6300A with smart monitoring.", badge: "Popular", price: "Contact for pricing", specs: { "Current": "800 – 6300A", "Breaking": "Up to 150 kA", "Trip Unit": "Micrologic 5/6/7, Micrologic X", "Communication": "Ethernet, Modbus", "Motorized": "Yes" }, features: ["Power metering Class 1", "Predictive maintenance", "Digital module", "Cybersecurity"], datasheetUrl: defaultDatasheetUrl },
  { id: "sc5", title: "Compact NSXm MCCB", brand: "Schneider", category: "Switchgear", description: "Compact molded case circuit breaker up to 160A for final distribution.", price: "₹5,500 – ₹25,000", specs: { "Current": "16 – 160A", "Breaking": "Up to 36 kA", "Poles": "3P / 4P", "Trip": "TM / Electronic (Micrologic)", "Width": "54 mm" }, features: ["Visi-trip indicator", "Toggle padlocking", "Earth leakage module", "Rotary handle"], datasheetUrl: defaultDatasheetUrl },
  { id: "sc6", title: "Magelis GTU HMI", brand: "Schneider", category: "HMI & SCADA", description: "Universal HMI panels from 7\" to 19\" with multi-touch and wide viewing angle.", price: "₹35,000 – ₹2,80,000", specs: { "Models": "GTU2200 (7\"), GTU2300, GTU2400 (10\"), GTU2500 (15\"), GTU2600 (19\")", "Resolution": "Up to 1280×1024", "Touch": "Capacitive multi-touch", "OS": "Linux embedded", "Ports": "2× Ethernet, USB, Serial" }, features: ["Vijeo Designer", "Widget-based development", "Remote access", "Alarm management"], datasheetUrl: defaultDatasheetUrl },
  { id: "sc7", title: "Harmony XB5 Push Buttons", brand: "Schneider", category: "Safety", description: "Ø22 mm pushbuttons and pilot lights with ChromoFlair colour-changing bezel.", price: "₹350 – ₹2,500", specs: { "Diameter": "22 mm", "Protection": "IP65/IP69K", "Contact": "1 NO / 1 NC", "Mounting": "Panel", "Life": "1 million cycles" }, features: ["ChromoFlair finish", "Spring-clamp terminals", "LED indicator", "E-stop variants"], datasheetUrl: defaultDatasheetUrl },
  { id: "sc8", title: "PM5560 Power Meter", brand: "Schneider", category: "Power Distribution", description: "High-performance power and energy meter with web pages and 0.2S accuracy.", price: "₹85,000", specs: { "Accuracy": "Class 0.2S", "Display": "Color touchscreen", "Communication": "Ethernet, Modbus", "Logging": "Onboard logging", "Waveform": "Yes" }, features: ["Power quality analysis", "Web interface", "Alarm management", "Multi-tariff metering"], datasheetUrl: defaultDatasheetUrl },
  { id: "sc9", title: "TeSys D Contactor", brand: "Schneider", category: "Switchgear", description: "3-pole contactor for motor control up to 150A with wide accessory range.", price: "₹1,200 – ₹18,000", specs: { "Models": "LC1D09–LC1D150", "Current": "9 – 150A", "Voltage": "Up to 690V", "Poles": "3P", "Coil": "AC/DC", "Mounting": "DIN rail / Plate" }, features: ["EverLink terminals", "Auxiliary contacts", "Overload relay pairing", "Reversing kits"], datasheetUrl: defaultDatasheetUrl },
  { id: "sc10", title: "Preventa XPS Safety Controller", brand: "Schneider", category: "Safety", description: "Configurable safety controller for multi-zone machine safety up to SIL 3.", price: "₹65,000 – ₹1,80,000", specs: { "Inputs": "Up to 128", "Outputs": "Up to 32", "Safety": "SIL 3 / PLe", "Configuration": "SoSafe software", "Communication": "EtherNet/IP, Modbus" }, features: ["Graphical configuration", "Expandable I/O", "Diagnostics web server", "USB commissioning"], datasheetUrl: defaultDatasheetUrl },
  { id: "sc11", title: "Acti9 iC60 MCB", brand: "Schneider", category: "Power Distribution", description: "Miniature circuit breaker for residential and commercial final distribution.", price: "₹450 – ₹3,200", specs: { "Current": "1 – 63A", "Breaking": "10 kA", "Curves": "B, C, D", "Poles": "1P – 4P", "Width": "18 mm/pole" }, features: ["Visi-trip indicator", "Clip-on accessories", "Top/bottom connection", "DIN rail mount"], datasheetUrl: defaultDatasheetUrl },

  // ── ROCKWELL ──
  { id: "r1", title: "ControlLogix 5580", brand: "Rockwell", category: "PLC & Controllers", description: "High-performance controller for large, complex automation and motion applications.", badge: "Premium", price: "Contact for pricing", specs: { "Model Numbers": "1756-L81E, L82E, L83E, L84E, L85E; L81EP/L83EP/L85EP (process); L81EK (conformal)", "Memory": "Up to 300 MB", "I/O": "Up to 256K points", "Communication": "EtherNet/IP", "Motion": "Up to 256 axes", "Programming": "Studio 5000" }, features: ["CIP Security", "Dual Ethernet ports", "Time synchronization", "High availability"], datasheetUrl: defaultDatasheetUrl },
  { id: "r2", title: "CompactLogix 5380", brand: "Rockwell", category: "PLC & Controllers", description: "Mid-range controller with integrated motion, safety, and process control.", price: "₹85,000 – ₹3,50,000", specs: { "Model Numbers": "5069-L306ER, L310ER, L320ER, L330ER, L340ER, L350ER, L380ER, L3100ER", "Memory": "Up to 80 MB", "I/O": "Up to 120K", "Communication": "EtherNet/IP", "Motion": "Up to 32 axes", "Safety": "SIL 2/3 (Guard variants)" }, features: ["Compact form factor", "Integrated safety", "Information-enabled", "Dual Ethernet"], datasheetUrl: defaultDatasheetUrl },
  { id: "r3", title: "PowerFlex 525 Drive", brand: "Rockwell", category: "Drives & Motors", description: "Compact AC drive for simple machine-level applications from 0.4 to 22 kW.", price: "₹18,000 – ₹1,20,000", specs: { "Power": "0.4 – 22 kW", "Voltage": "100 – 600V", "Control": "V/Hz, Sensorless Vector", "Safety": "Safe Torque Off", "Communication": "EtherNet/IP embedded" }, features: ["USB programming", "Quick connect wiring", "Embedded EtherNet/IP", "Energy monitoring"], datasheetUrl: defaultDatasheetUrl },
  { id: "r4", title: "PowerFlex 755 Drive", brand: "Rockwell", category: "Drives & Motors", description: "High-performance drive for demanding industrial applications up to 3500 kW.", price: "₹3,50,000 – ₹50,00,000", specs: { "Power": "0.75 – 3500 kW", "Voltage": "400 – 690V", "Control": "FOC, Sensorless Vector", "Safety": "CIP Safety SIL 3", "Cooling": "Air / Liquid" }, features: ["Predictive diagnostics", "Regenerative option", "Multi-motor control", "CIP Motion ready"], datasheetUrl: defaultDatasheetUrl },
  { id: "r5", title: "PanelView Plus 7 HMI", brand: "Rockwell", category: "HMI & SCADA", description: "Graphic terminal from 4\" to 19\" for machine-level operator interface.", price: "₹45,000 – ₹3,00,000", specs: { "Models": "2711P (4\"), 2711P-K (7\"), 2711P-T (10\"), 2711P-B (15\"), 2711P-B (19\")", "Resolution": "Up to 1440×900", "Memory": "512 MB", "Communication": "EtherNet/IP, Serial", "OS": "Windows CE" }, features: ["FactoryTalk View ME", "Alarm management", "Multi-language", "Remote monitoring"], datasheetUrl: defaultDatasheetUrl },
  { id: "r6", title: "Stratix 5700 Switch", brand: "Rockwell", category: "Connectivity", description: "Managed industrial Ethernet switch optimized for EtherNet/IP networks.", price: "₹55,000 – ₹2,50,000", specs: { "Ports": "6 – 20 GbE", "Speed": "10/100/1000 Mbps", "Management": "Cisco IOS", "Redundancy": "DLR, REP, RSTP", "Temperature": "-40 to +60°C" }, features: ["CIP-based management", "NAT support", "QoS", "Network Address Translation"], datasheetUrl: defaultDatasheetUrl },
  { id: "r7", title: "GuardLogix 5580 Safety", brand: "Rockwell", category: "Safety", description: "Safety controller providing SIL 3/PLe safety in the Logix platform.", price: "Contact for pricing", specs: { "Safety Level": "SIL 3 / PLe Cat 4", "Chassis": "1756 GuardLogix", "I/O": "Guard I/O modules", "Communication": "CIP Safety", "Programming": "Studio 5000" }, features: ["Integrated safety & standard", "Safety networking", "Safety instruction set", "High availability"], datasheetUrl: defaultDatasheetUrl },
  { id: "r8", title: "POINT Guard I/O", brand: "Rockwell", category: "Safety", description: "EtherNet/IP safety I/O modules for distributed safety applications.", price: "₹15,000 – ₹45,000/module", specs: { "Safety": "SIL 3 / PLe", "Communication": "CIP Safety over EtherNet/IP", "Modules": "1732E-IB8M8SOED, 1732E-OB8M8SOED, etc.", "Mounting": "DIN rail", "Protection": "IP20" }, features: ["Safety-rated I/O", "Ring topology", "Diagnostics", "Hot-swap capability"], datasheetUrl: defaultDatasheetUrl },
  { id: "r9", title: "Kinetix 5700 Servo Drive", brand: "Rockwell", category: "Drives & Motors", description: "Integrated servo drive for CIP Motion with safety functions on EtherNet/IP.", price: "₹1,80,000 – ₹5,00,000", specs: { "Power": "Up to 45 kW", "Communication": "CIP Motion", "Safety": "CIP Safety", "Feedback": "Multi-turn absolute", "Control": "Position, Velocity, Torque" }, features: ["Integrated safety", "Single-cable technology", "Auto-tuning", "Safe motion functions"], datasheetUrl: defaultDatasheetUrl },
  { id: "r10", title: "Micro850 Controller", brand: "Rockwell", category: "PLC & Controllers", description: "Entry-level programmable controller for standalone machine applications.", price: "₹15,000 – ₹35,000", specs: { "Models": "2080-LC30, LC50, LC70 (20–72 I/O)", "I/O": "Up to 132 points", "Communication": "Ethernet, Serial", "Memory": "20 KB", "Programming": "CCW" }, features: ["Low cost of entry", "Embedded Ethernet", "LCD display", "MicroSD support"], datasheetUrl: defaultDatasheetUrl },

  // ── MITSUBISHI ──
  { id: "m1", title: "MELSEC iQ-R Series PLC", brand: "Mitsubishi", category: "PLC & Controllers", description: "Next-gen controller with 0.98 ns processing and built-in database connectivity.", badge: "New", price: "Contact for pricing", specs: { "Model Numbers": "R08CPU, R16CPU, R32CPU, R120CPU; R08EN/R16EN/R32EN/R120EN (Ethernet); R08P/R16P/R32P/R120P (Process); R08SF/R16SF (Safety)", "Scan Time": "0.98 ns/step", "Memory": "Up to 80 MB", "I/O": "Up to 16,384 points", "Communication": "CC-Link IE TSN", "Programming": "GX Works3" }, features: ["SFC program execution", "Built-in MES interface", "Hot swap CPU", "SD card logging"], datasheetUrl: defaultDatasheetUrl },
  { id: "m2", title: "MELSEC iQ-F FX5U PLC", brand: "Mitsubishi", category: "PLC & Controllers", description: "Compact PLC with built-in high-speed I/O and analog for small-to-mid machines.", badge: "Best Seller", price: "₹18,000 – ₹55,000", specs: { "Models": "FX5U-32MR/ES, FX5U-64MR/ES, FX5U-80MR/ES (and MT, MT/ES)", "I/O": "32–512 points", "Speed": "34 ns/instruction", "Analog": "Built-in 2ch", "Communication": "Ethernet, RS-485", "Programming": "GX Works3" }, features: ["Built-in positioning", "Simple motion", "Data logging", "SD card support"], datasheetUrl: defaultDatasheetUrl },
  { id: "m3", title: "GOT2000 HMI Series", brand: "Mitsubishi", category: "HMI & SCADA", description: "Multi-touch HMI with gesture operation and high-resolution widescreen display.", price: "₹40,000 – ₹2,50,000", specs: { "Models": "GT27 (15\"), GT25 (12\"), GT23 (10\"), GT21 (8\"), GT2107 (5.7\")", "Resolution": "Up to 1024×768", "Touch": "Multi-touch capacitive", "Memory": "128 MB", "Ports": "Ethernet, USB, Serial" }, features: ["Gesture operation", "Screen video recording", "Remote monitoring", "Multi-channel"], datasheetUrl: defaultDatasheetUrl },
  { id: "m4", title: "FR-A800 Inverter", brand: "Mitsubishi", category: "Drives & Motors", description: "Premium AC inverter with real sensorless vector control and advanced auto-tuning.", price: "₹35,000 – ₹8,00,000", specs: { "Power": "0.4 – 500 kW", "Voltage": "200 – 400V (FR-A820/840)", "Control": "Real sensorless vector, PM motor", "Safety": "STO", "Communication": "CC-Link, Ethernet (option)" }, features: ["Real sensorless vector", "PM motor control", "Energy saving", "Lifecycle monitoring"], datasheetUrl: defaultDatasheetUrl },
  { id: "m5", title: "MR-J5 Servo Amplifier", brand: "Mitsubishi", category: "Drives & Motors", description: "Next-gen servo system with 3.5 kHz frequency response and network flexibility.", price: "₹45,000 – ₹2,00,000", specs: { "Models": "MR-J5W1-_G (50W–7kW), MR-J5-_G (100W–55kW)", "Response": "3.5 kHz", "Communication": "CC-Link IE TSN", "Encoder": "26-bit absolute", "Control": "Position, Speed, Torque" }, features: ["Vibration suppression", "One-touch tuning", "Predictive maintenance", "Multi-network support"], datasheetUrl: defaultDatasheetUrl },
  { id: "m6", title: "QS Safety PLC", brand: "Mitsubishi", category: "Safety", description: "Safety controller achieving SIL 3 for machine and process safety applications.", price: "₹1,20,000", specs: { "Safety": "SIL 3 / PLe", "I/O": "Safety DI/DO modules", "Communication": "CC-Link Safety", "Scan": "10 ms", "Programming": "GX Works3" }, features: ["Dual-channel processing", "Safety networking", "Diagnostics", "Easy migration"], datasheetUrl: defaultDatasheetUrl },
  { id: "m7", title: "CC-Link IE TSN Module", brand: "Mitsubishi", category: "Connectivity", description: "Time-Sensitive Networking module for deterministic industrial Ethernet communication.", price: "₹35,000", specs: { "Standard": "CC-Link IE TSN", "Speed": "1 Gbps", "Topology": "Star, Line, Ring", "TSN": "IEEE 802.1", "Compatibility": "CC-Link IE Field" }, features: ["Time synchronization", "Mixed traffic", "Gigabit speed", "Seamless migration"], datasheetUrl: defaultDatasheetUrl },
  { id: "m8", title: "NZ2MF Metering Module", brand: "Mitsubishi", category: "Power Distribution", description: "Energy measuring module for multi-circuit monitoring in distribution panels.", price: "₹42,000", specs: { "Circuits": "Up to 32", "Accuracy": "Class 1", "Communication": "CC-Link IE", "Parameters": "V, I, W, Wh, PF", "Mounting": "Panel" }, features: ["Multi-circuit monitoring", "Demand control", "Energy visualization", "CSV export"], datasheetUrl: defaultDatasheetUrl },
  { id: "m9", title: "WS0-XTIO Safety I/O", brand: "Mitsubishi", category: "Safety", description: "Distributed safety I/O terminal with CC-Link IE Safety communication.", price: "₹12,000 – ₹28,000/module", specs: { "Safety": "SIL 3 / PLe", "Communication": "CC-Link IE Safety", "Modules": "DI, DO, AI", "Cycle": "10 ms", "Protection": "IP20" }, features: ["Compact design", "Tool-less wiring", "LED diagnostics", "Hot-swap capable"], datasheetUrl: defaultDatasheetUrl },
  { id: "m10", title: "MELSoft iQ AppPortal", brand: "Mitsubishi", category: "HMI & SCADA", description: "PC-based SCADA/MES interface for production visualization and data analytics.", price: "₹2,50,000", specs: { "Platform": "Windows PC", "Database": "SQL Server", "Clients": "Web browser", "Protocols": "OPC UA, SLMP", "Trending": "Historical & real-time" }, features: ["Dashboard builder", "KPI monitoring", "Report generation", "Multi-site support"], datasheetUrl: defaultDatasheetUrl },
  { id: "m11", title: "AJ65SBT Sensor Block", brand: "Mitsubishi", category: "Sensors", description: "CC-Link compatible sensor terminal block for distributed I/O collection.", price: "₹8,500", specs: { "Models": "AJ65SBT-64AD, AJ65SBT-64DIN, etc.", "Inputs": "16 DI / 16 DO (mixed)", "Communication": "CC-Link V2", "Speed": "10 Mbps", "Mounting": "DIN rail" }, features: ["Mixed I/O", "Screw terminals", "LED indicators", "Compact size"], datasheetUrl: defaultDatasheetUrl },

  // ── HONEYWELL ──
  { id: "h1", title: "ControlEdge PLC", brand: "Honeywell", category: "PLC & Controllers", description: "Compact controller for small process applications with native OPC UA support.", price: "₹65,000 – ₹2,00,000", specs: { "I/O": "Up to 500 points", "Communication": "OPC UA, Modbus", "Memory": "32 MB", "Programming": "CODESYS V3", "Cybersecurity": "IEC 62443" }, features: ["Built-in OPC UA", "Cybersecurity certified", "Web-based config", "SD card backup"], datasheetUrl: defaultDatasheetUrl },
  { id: "h2", title: "Experion PKS SCADA", brand: "Honeywell", category: "HMI & SCADA", description: "Process knowledge system for process control, SCADA, and safety applications.", badge: "Enterprise", price: "Contact for pricing", specs: { "Architecture": "Distributed", "Servers": "Redundant pair", "Clients": "Web & thick", "Protocols": "OPC, Modbus, HART", "Safety": "Integrated SIS" }, features: ["Abnormal situation management", "Alarm rationalization", "Batch automation", "Cybersecurity suite"], datasheetUrl: defaultDatasheetUrl },
  { id: "h3", title: "Safety Manager SC", brand: "Honeywell", category: "Safety", description: "SIL 3 certified safety controller for critical process industries and machine safety.", badge: "Popular", price: "₹3,50,000 – ₹12,00,000", specs: { "Safety": "SIL 3 / IEC 61511", "I/O": "STIO modules", "Communication": "FTE, Modbus", "Diagnostics": "100% online", "Redundancy": "TMR architecture" }, features: ["Triple modular redundancy", "Online maintenance", "SOE recording", "Lifecycle management"], datasheetUrl: defaultDatasheetUrl },
  { id: "h4", title: "STT850 Temperature Transmitter", brand: "Honeywell", category: "Sensors", description: "Smart temperature transmitter with dual sensor input and advanced diagnostics.", price: "₹22,000", specs: { "Input": "RTD, TC, mV, Ohm", "Output": "4-20 mA + HART", "Accuracy": "±0.01% span", "Housing": "SS / Aluminum", "Certification": "ATEX, IECEx" }, features: ["Dual sensor input", "Sensor drift alert", "Hot backup", "Process alerts"], datasheetUrl: defaultDatasheetUrl },
  { id: "h5", title: "ST800 Pressure Transmitter", brand: "Honeywell", category: "Sensors", description: "Smart pressure transmitter for gauge, absolute, and differential measurement.", price: "₹35,000", specs: { "Range": "0.1 – 700 bar", "Output": "4-20 mA + HART", "Accuracy": "±0.04%", "Wetted": "SS 316L", "Protocol": "HART 7, DE" }, features: ["10-year stability", "SIL 2/3 rated", "LCD display", "Configuration via DDL"], datasheetUrl: defaultDatasheetUrl },
  { id: "h6", title: "Versaflow Mag 5100", brand: "Honeywell", category: "Sensors", description: "Electromagnetic flowmeter for conductive liquid measurement with pulsed DC technology.", price: "₹55,000 – ₹2,50,000", specs: { "Size": "DN 3 – 3000 mm", "Accuracy": "±0.2%", "Output": "4-20 mA, HART, Modbus", "Liner": "PFA, PTFE, Rubber", "Protection": "IP67/68" }, features: ["Bi-directional flow", "Empty pipe detection", "Self-diagnostics", "Batching function"], datasheetUrl: defaultDatasheetUrl },
  { id: "h7", title: "C300 Controller", brand: "Honeywell", category: "PLC & Controllers", description: "High-performance process controller for Experion PKS with redundancy and SIL 2 rating.", price: "₹4,50,000", specs: { "I/O": "Up to 64 CIOB", "Scan": "100 ms – 50 ms", "Redundancy": "Hot standby", "Safety": "SIL 2", "Communication": "FTE Ethernet" }, features: ["Control/IO in one", "Fault tolerant Ethernet", "Online download", "Universal I/O option"], datasheetUrl: defaultDatasheetUrl },
  { id: "h8", title: "Maxon Industrial Burner", brand: "Honeywell", category: "Safety", description: "Industrial combustion equipment with flame safeguard and precise temperature control.", price: "₹1,50,000 – ₹8,00,000", specs: { "Fuel": "Gas / Oil / Dual", "Capacity": "50 kW – 50 MW", "Control": "Modulating", "Safety": "SIL rated", "Certification": "CE, UL" }, features: ["Low NOx emission", "Flame monitoring", "Modular design", "Remote diagnostics"], datasheetUrl: defaultDatasheetUrl },
  { id: "h9", title: "OneWireless Adapter", brand: "Honeywell", category: "Connectivity", description: "Industrial wireless gateway for ISA100 Wireless field device integration.", price: "₹85,000", specs: { "Standard": "ISA100.11a", "Range": "Up to 250 m", "Devices": "Up to 100 per gateway", "Security": "AES-128 encryption", "Power": "24V DC / Solar" }, features: ["Mesh networking", "Self-healing", "Low power", "Coexistence management"], datasheetUrl: defaultDatasheetUrl },
  { id: "h10", title: "RTN200 Gas Analyzer", brand: "Honeywell", category: "Sensors", description: "Continuous gas analyzer for emissions and process monitoring with TDL technology.", price: "₹3,50,000", specs: { "Technology": "Tunable Diode Laser", "Gases": "O2, CO, CO2, NH3, H2O", "Response": "< 2 seconds", "Path": "In-situ", "Certification": "ATEX, IECEx" }, features: ["No sampling required", "Self-validation", "Low maintenance", "SIL 1 rated"], datasheetUrl: defaultDatasheetUrl },
  { id: "h11", title: "Enraf Servo Level Gauge", brand: "Honeywell", category: "Sensors", description: "High-accuracy tank gauging system for custody transfer and inventory management.", price: "₹4,50,000", specs: { "Accuracy": "±0.4 mm", "Range": "Up to 45 m", "Communication": "Modbus, HART, Enraf", "Certification": "Custody transfer", "Temperature": "Multi-spot" }, features: ["Custody transfer certified", "Water interface detection", "Density measurement", "Lightning protection"], datasheetUrl: defaultDatasheetUrl },

  // ── ELCO (I/O Modules – elcoautomation.com) ──
  { id: "el1", title: "IO-Link Solution", brand: "ELCO", category: "I/O Modules", description: "IO-Link master and device portfolio for flexible sensor/actuator integration and parameterization.", price: "Contact for pricing", specs: { "Protocol": "IO-Link 1.1", "Ports": "4–8 per master", "Integration": "PROFINET, EtherCAT, EtherNet/IP", "Protection": "IP20 / IP67", "Diagnostics": "Port-level", "Variants": "Block, in-line, hub" }, features: ["Tool-free wiring", "Remote parameterization", "Condition monitoring", "Modular expansion"], datasheetUrl: defaultDatasheetUrl },
  { id: "el2", title: "IP67 Integrated I/O", brand: "ELCO", category: "I/O Modules", description: "IP67-rated distributed I/O for direct field installation without control cabinet.", badge: "Popular", price: "Contact for pricing", specs: { "Protection": "IP67", "Protocols": "PROFINET, EtherCAT, EtherNet/IP, Modbus TCP", "I/O Types": "Digital, analog, special", "Mounting": "Field mount", "Channels": "Integrated blocks" }, features: ["Direct field mounting", "Reduced cabinet space", "Industrial Ethernet", "Wide temperature range"], datasheetUrl: defaultDatasheetUrl },
  { id: "el3", title: "IP20 Modular I/O", brand: "ELCO", category: "I/O Modules", description: "Modular IP20 I/O system for control cabinet mounting with high channel density.", price: "Contact for pricing", specs: { "Protection": "IP20", "Backplane": "PROFINET, EtherCAT, EtherNet/IP", "Modules": "DI, DO, AI, AO, special", "Width": "Modular per channel", "Hot Swap": "Yes" }, features: ["Modular expansion", "Mixed signal types", "Diagnostics", "DIN rail mount"], datasheetUrl: defaultDatasheetUrl },
  { id: "el4", title: "IP20 Compact I/O", brand: "ELCO", category: "I/O Modules", description: "Compact IP20 I/O blocks for space-limited cabinets with industrial Ethernet connectivity.", price: "Contact for pricing", specs: { "Protection": "IP20", "Protocols": "PROFINET, EtherCAT, EtherNet/IP, Modbus TCP", "Form": "Compact block", "I/O": "Digital, analog", "Speed": "Real-time capable" }, features: ["Space-saving", "Fast commissioning", "LED status", "Screw/spring terminals"], datasheetUrl: defaultDatasheetUrl },

  // ── EUCHNER (Safety – euchner.in) ──
  { id: "eu1", title: "CES-AR Safety Switch", brand: "EUCHNER", category: "Safety", description: "Transponder-coded magnetic safety switch for door and guard monitoring.", badge: "Popular", price: "Contact for pricing", specs: { "Model Example": "CES-AR-C01-AH-SA (098941), CES-AR-C01-CH-SA", "Safety Level": "SIL 3 / Cat 4 / PLe", "Actuation": "Non-contact transponder", "Contacts": "2 NO safety + monitoring", "Protection": "IP67", "Series": "Up to 20 switches" }, features: ["Tamper-resistant", "No wear contacts", "High switching frequency", "Flexible mounting"], datasheetUrl: defaultDatasheetUrl },
  { id: "eu2", title: "E-STOP Pushbutton MGB", brand: "EUCHNER", category: "Safety", description: "Emergency stop pushbutton with positive break contacts and robust metal housing.", price: "Contact for pricing", specs: { "Model Example": "MGB-L1C-ARA-R (109798)", "Standard": "IEC 60947-5-5", "Contacts": "Positive break, 2 NO + 2 NC", "Protection": "IP65", "Diameter": "40 mm", "Release": "Turn-to-reset" }, features: ["Positive break", "Twist release", "High visibility", "Reliable shutdown"], datasheetUrl: defaultDatasheetUrl },
  { id: "eu3", title: "Safety Door Handle TZ", brand: "EUCHNER", category: "Safety", description: "Safety door handle with integrated switch for guard locking and access control.", price: "Contact for pricing", specs: { "Function": "Guard locking + monitoring", "Safety": "Cat 4 / PLe", "Locking Force": "Up to 3000 N", "Protection": "IP65", "Release": "Electrical or mechanical" }, features: ["Guard locking", "Trapped key option", "Status feedback", "Durable design"], datasheetUrl: defaultDatasheetUrl },
  { id: "eu4", title: "Key-Operated Switch CKS", brand: "EUCHNER", category: "Safety", description: "Key-operated safety switch for mode selection and access control.", price: "Contact for pricing", specs: { "Positions": "2–4 positions", "Key": "Coded", "Contacts": "Safety + auxiliary", "Protection": "IP65", "Mounting": "Panel" }, features: ["Coded key system", "Mode selection", "Access control", "Compact design"], datasheetUrl: defaultDatasheetUrl },

  // ── SICK (Sensors – sick.com/in) ──
  { id: "sk1", title: "W12 Photoelectric Sensor", brand: "SICK", category: "Sensors", description: "Compact photoelectric sensor for detection in tight spaces with background suppression.", badge: "Best Seller", price: "Contact for pricing", specs: { "Models": "WT12L-2B540, WTB12L (30–200 mm)", "Type": "Background suppression laser", "Range": "30–200 mm", "Light Source": "Red laser 650 nm", "Output": "PNP/NPN", "Protection": "IP67/IP69K", "Switching": "2,500 Hz" }, features: ["Compact housing", "Background suppression", "Quick connect", "Reliable switching"], datasheetUrl: defaultDatasheetUrl },
  { id: "sk2", title: "IME Inductive Proximity Sensor", brand: "SICK", category: "Sensors", description: "Inductive proximity sensor for metal detection with flush or non-flush mounting.", price: "Contact for pricing", specs: { "Models": "IME12-04BPSZW2KS31 (M12, 4 mm), IME18, IME30", "Sensing Range": "2–15 mm", "Frequency": "Up to 2 kHz", "Output": "PNP/NPN", "Protection": "IP65/IP67", "Housing": "M8–M30" }, features: ["Metal detection", "Short-circuit protection", "Weld-field immune", "Long service life"], datasheetUrl: defaultDatasheetUrl },
  { id: "sk3", title: "DBS60 Distance Sensor", brand: "SICK", category: "Sensors", description: "Compact distance sensor for precise measurement and level detection.", price: "Contact for pricing", specs: { "Models": "DBS60E-S4CK (analog/IO-Link)", "Range": "20–600 mm", "Accuracy": "±3 mm", "Output": "4–20 mA / IO-Link", "Protection": "IP67", "Technology": "ToF" }, features: ["Analog + IO-Link", "Background suppression", "Compact", "Process monitoring"], datasheetUrl: defaultDatasheetUrl },
  { id: "sk4", title: "DFS60 Safety Light Curtain", brand: "SICK", category: "Safety", description: "Safety light curtain for point-of-operation guarding and perimeter access.", price: "Contact for pricing", specs: { "Resolution": "14–90 mm (finger/hand/body)", "Range": "Up to 12 m", "Safety": "Cat 4 / PLe", "Beams": "20–160", "Response": "≤ 14 ms" }, features: ["Finger/hand/body protection", "Muting", "Cascading", "Easy alignment"], datasheetUrl: defaultDatasheetUrl },
  { id: "sk5", title: "ATM60 Absolute Encoder", brand: "SICK", category: "Sensors", description: "Absolute multiturn encoder for position feedback on motors and axes.", price: "Contact for pricing", specs: { "Resolution": "Up to 25 bit", "Interface": "SSI, PROFIBUS, PROFINET", "Protection": "IP65/IP67", "Shaft": "Hollow / solid", "Turns": "Multiturn, no battery" }, features: ["Absolute position", "No battery", "Industrial interfaces", "Robust housing"], datasheetUrl: defaultDatasheetUrl },
];

export function getProductById(products: Product[], id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getSimilarProducts(products: Product[], current: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.id !== current.id && (p.brand === current.brand || p.category === current.category))
    .slice(0, limit);
}
